
# General page configuration
page_title: "Nuestra Historia en Acertijos"
welcome_message: "Nos quedamos a una más... una copa más, un recuerdo más y una historia juntos."

# Riddle definitions
riddles:
  - id: 1
    title: "Acertijo 1: Primeros experimentos"
    description: "Para llegar a alcanzar la maestría en el arte del frasco, primero hay que hacer prácticas, experimentos y aprendizajes. En el laboratorio aprendimos a tomar las mejores mezclas en vasos de precipitados ¿Podéis encontrar la ubicación correcta de nuestro lugar de prácticas?\n (Sólo necesitamos el número entero de la latitud y longitud)"
    type: "dual_input"
    correct_answer: 37
    input_labels:
      - "Latitud"
      - "Longitud"

  - id: 2
    title: "Acertijo 2: De antro en antro"
    description: "La Llama y el Eljomar eran nuestros antros de preferencia, pero, a veces, había que probar el mainstream. ¿Cuánto costaba el pack de 3 cervezas y nachos?"
    type: "single_input"
    image_url: "/images/restaurant_photo.jpeg"
    correct_answer: 3

  - id: 3
    title: "Acertijo 3: Un Recuerdo a Alta Velocidad"
    description: "Mirando esta foto, ¿puedes calcular la velocidad máxima que alcanzó el objeto (en km/h) que aparece desde el punto de vista de un espectador que está fuera del tren?"
    type: "single_input"
    image_url: "/images/dildo_photo.jpg"
    correct_answer: 300

# User feedback messages
success_message: "¡Has desbloqueado el recuerdo! Entrega este código a la persona encargada de daros la recompensa:"
error_message: "Mmm... La memoria falla y algunos detalles están un poco borrosos. ¡Inténtalo de nuevo!"
verify_button_text: "Verificar Respuestas"
